### ISSUE TITLE
Install mediainfo

### ISSUE THREAD

**Issue by thinkloop** [mbentley/docker-ums#21]
Hello, I am getting "unseekable stream" trying to play some videos in VLC android. The web says I need to `apt install mediainfo`. Will that be accessible by the docker container? Or is there another way to do it?

Thank you.

**Comment by mbentley** [comment]
Which image/tag are you using?

**Comment by thinkloop** [comment]
I am using this:

```
  ums:
    container_name: ums
    image: mbentley/ums    
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/ephemeral/video:/media         
      - /mnt/docker-data/ums/UMS.conf:/opt/ums/UMS.conf
      - /mnt/docker-data/ums/data:/opt/ums/data
      - /mnt/docker-data/ums/database:/opt/ums/database
    ports:
      - "5001:5001"   
      - "9001:9001"         
    environment:
      - FOLDER=/media
      - PORT=5001
      - NETWORK_INTERFACE=eno2
      - SET_MEDIA_PERMISSIONS=true
      - FORCE_CHOWN=true
 ```
